package extractor.DAO.mapper;

import extractor.model._event;

public interface _eventMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event
     *
     * @mbg.generated Mon Apr 29 16:50:42 CST 2019
     */
    int deleteByPrimaryKey(Integer eventid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event
     *
     * @mbg.generated Mon Apr 29 16:50:42 CST 2019
     */
    int insert(_event record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event
     *
     * @mbg.generated Mon Apr 29 16:50:42 CST 2019
     */
    int insertSelective(_event record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event
     *
     * @mbg.generated Mon Apr 29 16:50:42 CST 2019
     */
    _event selectByPrimaryKey(Integer eventid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event
     *
     * @mbg.generated Mon Apr 29 16:50:42 CST 2019
     */
    int updateByPrimaryKeySelective(_event record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event
     *
     * @mbg.generated Mon Apr 29 16:50:42 CST 2019
     */
    int updateByPrimaryKey(_event record);
}