package extractor.DAO.mapper;

import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

import extractor.model._event;
@Mapper
@Component
public interface _eventMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event
     *
     * @mbg.generated Thu Jul 25 17:54:41 CST 2019
     */
    int deleteByPrimaryKey(Integer eventid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event
     *
     * @mbg.generated Thu Jul 25 17:54:41 CST 2019
     */
    int insert(_event record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event
     *
     * @mbg.generated Thu Jul 25 17:54:41 CST 2019
     */
    int insertSelective(_event record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event
     *
     * @mbg.generated Thu Jul 25 17:54:41 CST 2019
     */
    _event selectByPrimaryKey(Integer eventid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event
     *
     * @mbg.generated Thu Jul 25 17:54:41 CST 2019
     */
    int updateByPrimaryKeySelective(_event record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event
     *
     * @mbg.generated Thu Jul 25 17:54:41 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(_event record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event
     *
     * @mbg.generated Thu Jul 25 17:54:41 CST 2019
     */
    int updateByPrimaryKey(_event record);
    _event getEventID(String eventname);
}