package extractor.DAO.mapper;

import java.util.List;

import extractor.model._exception;

public interface _exceptionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exception
     *
     * @mbg.generated Fri Jun 21 10:16:02 CST 2019
     */
    int deleteByPrimaryKey(Integer exceptionid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exception
     *
     * @mbg.generated Fri Jun 21 10:16:02 CST 2019
     */
    int insert(_exception record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exception
     *
     * @mbg.generated Fri Jun 21 10:16:02 CST 2019
     */
    int insertSelective(_exception record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exception
     *
     * @mbg.generated Fri Jun 21 10:16:02 CST 2019
     */
    _exception selectByPrimaryKey(Integer exceptionid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exception
     *
     * @mbg.generated Fri Jun 21 10:16:02 CST 2019
     */
    int updateByPrimaryKeySelective(_exception record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exception
     *
     * @mbg.generated Fri Jun 21 10:16:02 CST 2019
     */
    int updateByPrimaryKey(_exception record);
    
    List<_exception> selectByComp(Integer componentID);
}