package extractor.DAO.mapper;

import extractor.model._state;

public interface _stateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table state
     *
     * @mbg.generated Mon Apr 29 17:41:06 CST 2019
     */
    int deleteByPrimaryKey(Integer stateid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table state
     *
     * @mbg.generated Mon Apr 29 17:41:06 CST 2019
     */
    int insert(_state record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table state
     *
     * @mbg.generated Mon Apr 29 17:41:06 CST 2019
     */
    int insertSelective(_state record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table state
     *
     * @mbg.generated Mon Apr 29 17:41:06 CST 2019
     */
    _state selectByPrimaryKey(Integer stateid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table state
     *
     * @mbg.generated Mon Apr 29 17:41:06 CST 2019
     */
    int updateByPrimaryKeySelective(_state record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table state
     *
     * @mbg.generated Mon Apr 29 17:41:06 CST 2019
     */
    int updateByPrimaryKey(_state record);
}