package extractor.DAO.mapper;

import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

import extractor.model._task;

@Mapper
@Component
public interface _taskMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table task
	 *
	 * @mbg.generated Tue Apr 30 13:34:44 CST 2019
	 */
	int deleteByPrimaryKey(Integer taskid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table task
	 *
	 * @mbg.generated Tue Apr 30 13:34:44 CST 2019
	 */
	int insert(_task record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table task
	 *
	 * @mbg.generated Tue Apr 30 13:34:44 CST 2019
	 */
	int insertSelective(_task record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table task
	 *
	 * @mbg.generated Tue Apr 30 13:34:44 CST 2019
	 */
	_task selectByPrimaryKey(Integer taskid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table task
	 *
	 * @mbg.generated Tue Apr 30 13:34:44 CST 2019
	 */
	int updateByPrimaryKeySelective(_task record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table task
	 *
	 * @mbg.generated Tue Apr 30 13:34:44 CST 2019
	 */
	int updateByPrimaryKey(_task record);

	void setPartitionIDByTaskID(Integer taskid, Integer partitionid);
}