package extractor.DAO.mapper;

import extractor.model.portmap;
import extractor.model.portmapKey;

public interface portmapMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portmap
     *
     * @mbg.generated Tue May 14 22:28:28 CST 2019
     */
    int deleteByPrimaryKey(portmapKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portmap
     *
     * @mbg.generated Tue May 14 22:28:28 CST 2019
     */
    int insert(portmap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portmap
     *
     * @mbg.generated Tue May 14 22:28:28 CST 2019
     */
    int insertSelective(portmap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portmap
     *
     * @mbg.generated Tue May 14 22:28:28 CST 2019
     */
    portmap selectByPrimaryKey(portmapKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portmap
     *
     * @mbg.generated Tue May 14 22:28:28 CST 2019
     */
    int updateByPrimaryKeySelective(portmap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portmap
     *
     * @mbg.generated Tue May 14 22:28:28 CST 2019
     */
    int updateByPrimaryKey(portmap record);
}