package extractor.DAO.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

import extractor.model.propagation;
@Mapper
@Component
public interface propagationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propagation
     *
     * @mbg.generated Sun Jul 21 17:02:38 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propagation
     *
     * @mbg.generated Sun Jul 21 17:02:38 CST 2019
     */
    int insert(propagation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propagation
     *
     * @mbg.generated Sun Jul 21 17:02:38 CST 2019
     */
    int insertSelective(propagation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propagation
     *
     * @mbg.generated Sun Jul 21 17:02:38 CST 2019
     */
    propagation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propagation
     *
     * @mbg.generated Sun Jul 21 17:02:38 CST 2019
     */
    int updateByPrimaryKeySelective(propagation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propagation
     *
     * @mbg.generated Sun Jul 21 17:02:38 CST 2019
     */
    int updateByPrimaryKey(propagation record);
    List<propagation> selectByComponent(Integer componentid);
}