package extractor.DAO.mapper;

import extractor.model.transitionstate;

public interface transitionstateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transitionstate
     *
     * @mbg.generated Tue Apr 30 11:57:57 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transitionstate
     *
     * @mbg.generated Tue Apr 30 11:57:57 CST 2019
     */
    int insert(transitionstate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transitionstate
     *
     * @mbg.generated Tue Apr 30 11:57:57 CST 2019
     */
    int insertSelective(transitionstate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transitionstate
     *
     * @mbg.generated Tue Apr 30 11:57:57 CST 2019
     */
    transitionstate selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transitionstate
     *
     * @mbg.generated Tue Apr 30 11:57:57 CST 2019
     */
    int updateByPrimaryKeySelective(transitionstate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transitionstate
     *
     * @mbg.generated Tue Apr 30 11:57:57 CST 2019
     */
    int updateByPrimaryKey(transitionstate record);
}