package extractor.model;

public class errorpath {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column errorpath.id
     *
     * @mbg.generated Sun Jul 21 15:22:00 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column errorpath.startportid
     *
     * @mbg.generated Sun Jul 21 15:22:00 CST 2019
     */
    private String startportid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column errorpath.endportid
     *
     * @mbg.generated Sun Jul 21 15:22:00 CST 2019
     */
    private String endportid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column errorpath.componentid
     *
     * @mbg.generated Sun Jul 21 15:22:00 CST 2019
     */
    private String componentid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column errorpath.id
     *
     * @return the value of errorpath.id
     *
     * @mbg.generated Sun Jul 21 15:22:00 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column errorpath.id
     *
     * @param id the value for errorpath.id
     *
     * @mbg.generated Sun Jul 21 15:22:00 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column errorpath.startportid
     *
     * @return the value of errorpath.startportid
     *
     * @mbg.generated Sun Jul 21 15:22:00 CST 2019
     */
    public String getStartportid() {
        return startportid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column errorpath.startportid
     *
     * @param startportid the value for errorpath.startportid
     *
     * @mbg.generated Sun Jul 21 15:22:00 CST 2019
     */
    public void setStartportid(String startportid) {
        this.startportid = startportid == null ? null : startportid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column errorpath.endportid
     *
     * @return the value of errorpath.endportid
     *
     * @mbg.generated Sun Jul 21 15:22:00 CST 2019
     */
    public String getEndportid() {
        return endportid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column errorpath.endportid
     *
     * @param endportid the value for errorpath.endportid
     *
     * @mbg.generated Sun Jul 21 15:22:00 CST 2019
     */
    public void setEndportid(String endportid) {
        this.endportid = endportid == null ? null : endportid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column errorpath.componentid
     *
     * @return the value of errorpath.componentid
     *
     * @mbg.generated Sun Jul 21 15:22:00 CST 2019
     */
    public String getComponentid() {
        return componentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column errorpath.componentid
     *
     * @param componentid the value for errorpath.componentid
     *
     * @mbg.generated Sun Jul 21 15:22:00 CST 2019
     */
    public void setComponentid(String componentid) {
        this.componentid = componentid == null ? null : componentid.trim();
    }
}