package extractor.model;

public class portmapKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portmap.idnew_table
     *
     * @mbg.generated Tue May 14 22:28:28 CST 2019
     */
    private Integer idnewTable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portmap.sourcemodelType
     *
     * @mbg.generated Tue May 14 22:28:28 CST 2019
     */
    private String sourcemodeltype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portmap.idnew_table
     *
     * @return the value of portmap.idnew_table
     *
     * @mbg.generated Tue May 14 22:28:28 CST 2019
     */
    public Integer getIdnewTable() {
        return idnewTable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portmap.idnew_table
     *
     * @param idnewTable the value for portmap.idnew_table
     *
     * @mbg.generated Tue May 14 22:28:28 CST 2019
     */
    public void setIdnewTable(Integer idnewTable) {
        this.idnewTable = idnewTable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portmap.sourcemodelType
     *
     * @return the value of portmap.sourcemodelType
     *
     * @mbg.generated Tue May 14 22:28:28 CST 2019
     */
    public String getSourcemodeltype() {
        return sourcemodeltype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portmap.sourcemodelType
     *
     * @param sourcemodeltype the value for portmap.sourcemodelType
     *
     * @mbg.generated Tue May 14 22:28:28 CST 2019
     */
    public void setSourcemodeltype(String sourcemodeltype) {
        this.sourcemodeltype = sourcemodeltype == null ? null : sourcemodeltype.trim();
    }
}