package extractor.model;

public class portmap extends portmapKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portmap.sourceportname
     *
     * @mbg.generated Tue May 14 22:28:28 CST 2019
     */
    private String sourceportname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portmap.modeltype_corr
     *
     * @mbg.generated Tue May 14 22:28:28 CST 2019
     */
    private String modeltypeCorr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portmap.portname_corr
     *
     * @mbg.generated Tue May 14 22:28:28 CST 2019
     */
    private String portnameCorr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portmap.sourceportname
     *
     * @return the value of portmap.sourceportname
     *
     * @mbg.generated Tue May 14 22:28:28 CST 2019
     */
    public String getSourceportname() {
        return sourceportname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portmap.sourceportname
     *
     * @param sourceportname the value for portmap.sourceportname
     *
     * @mbg.generated Tue May 14 22:28:28 CST 2019
     */
    public void setSourceportname(String sourceportname) {
        this.sourceportname = sourceportname == null ? null : sourceportname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portmap.modeltype_corr
     *
     * @return the value of portmap.modeltype_corr
     *
     * @mbg.generated Tue May 14 22:28:28 CST 2019
     */
    public String getModeltypeCorr() {
        return modeltypeCorr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portmap.modeltype_corr
     *
     * @param modeltypeCorr the value for portmap.modeltype_corr
     *
     * @mbg.generated Tue May 14 22:28:28 CST 2019
     */
    public void setModeltypeCorr(String modeltypeCorr) {
        this.modeltypeCorr = modeltypeCorr == null ? null : modeltypeCorr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portmap.portname_corr
     *
     * @return the value of portmap.portname_corr
     *
     * @mbg.generated Tue May 14 22:28:28 CST 2019
     */
    public String getPortnameCorr() {
        return portnameCorr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portmap.portname_corr
     *
     * @param portnameCorr the value for portmap.portname_corr
     *
     * @mbg.generated Tue May 14 22:28:28 CST 2019
     */
    public void setPortnameCorr(String portnameCorr) {
        this.portnameCorr = portnameCorr == null ? null : portnameCorr.trim();
    }
}