package extractor.model;

public class propagation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column propagation.id
     *
     * @mbg.generated Sun Jul 21 17:02:38 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column propagation.linkpointid
     *
     * @mbg.generated Sun Jul 21 17:02:38 CST 2019
     */
    private String linkpointid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column propagation.faultname
     *
     * @mbg.generated Sun Jul 21 17:02:38 CST 2019
     */
    private String faultname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column propagation.componentid
     *
     * @mbg.generated Sun Jul 21 17:02:38 CST 2019
     */
    private String componentid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column propagation.id
     *
     * @return the value of propagation.id
     *
     * @mbg.generated Sun Jul 21 17:02:38 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column propagation.id
     *
     * @param id the value for propagation.id
     *
     * @mbg.generated Sun Jul 21 17:02:38 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column propagation.linkpointid
     *
     * @return the value of propagation.linkpointid
     *
     * @mbg.generated Sun Jul 21 17:02:38 CST 2019
     */
    public String getLinkpointid() {
        return linkpointid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column propagation.linkpointid
     *
     * @param linkpointid the value for propagation.linkpointid
     *
     * @mbg.generated Sun Jul 21 17:02:38 CST 2019
     */
    public void setLinkpointid(String linkpointid) {
        this.linkpointid = linkpointid == null ? null : linkpointid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column propagation.faultname
     *
     * @return the value of propagation.faultname
     *
     * @mbg.generated Sun Jul 21 17:02:38 CST 2019
     */
    public String getFaultname() {
        return faultname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column propagation.faultname
     *
     * @param faultname the value for propagation.faultname
     *
     * @mbg.generated Sun Jul 21 17:02:38 CST 2019
     */
    public void setFaultname(String faultname) {
        this.faultname = faultname == null ? null : faultname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column propagation.componentid
     *
     * @return the value of propagation.componentid
     *
     * @mbg.generated Sun Jul 21 17:02:38 CST 2019
     */
    public String getComponentid() {
        return componentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column propagation.componentid
     *
     * @param componentid the value for propagation.componentid
     *
     * @mbg.generated Sun Jul 21 17:02:38 CST 2019
     */
    public void setComponentid(String componentid) {
        this.componentid = componentid == null ? null : componentid.trim();
    }
}