package extractor.model;

public class slkstate {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column slkstate.ID
     *
     * @mbg.generated Fri Jul 26 16:10:58 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column slkstate.taskid
     *
     * @mbg.generated Fri Jul 26 16:10:58 CST 2019
     */
    private String taskid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column slkstate.faultstate
     *
     * @mbg.generated Fri Jul 26 16:10:58 CST 2019
     */
    private String faultstate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column slkstate.isparalle
     *
     * @mbg.generated Fri Jul 26 16:10:58 CST 2019
     */
    private String isparalle;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column slkstate.ID
     *
     * @return the value of slkstate.ID
     *
     * @mbg.generated Fri Jul 26 16:10:58 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column slkstate.ID
     *
     * @param id the value for slkstate.ID
     *
     * @mbg.generated Fri Jul 26 16:10:58 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column slkstate.taskid
     *
     * @return the value of slkstate.taskid
     *
     * @mbg.generated Fri Jul 26 16:10:58 CST 2019
     */
    public String getTaskid() {
        return taskid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column slkstate.taskid
     *
     * @param taskid the value for slkstate.taskid
     *
     * @mbg.generated Fri Jul 26 16:10:58 CST 2019
     */
    public void setTaskid(String taskid) {
        this.taskid = taskid == null ? null : taskid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column slkstate.faultstate
     *
     * @return the value of slkstate.faultstate
     *
     * @mbg.generated Fri Jul 26 16:10:58 CST 2019
     */
    public String getFaultstate() {
        return faultstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column slkstate.faultstate
     *
     * @param faultstate the value for slkstate.faultstate
     *
     * @mbg.generated Fri Jul 26 16:10:58 CST 2019
     */
    public void setFaultstate(String faultstate) {
        this.faultstate = faultstate == null ? null : faultstate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column slkstate.isparalle
     *
     * @return the value of slkstate.isparalle
     *
     * @mbg.generated Fri Jul 26 16:10:58 CST 2019
     */
    public String getIsparalle() {
        return isparalle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column slkstate.isparalle
     *
     * @param isparalle the value for slkstate.isparalle
     *
     * @mbg.generated Fri Jul 26 16:10:58 CST 2019
     */
    public void setIsparalle(String isparalle) {
        this.isparalle = isparalle == null ? null : isparalle.trim();
    }
}