package extractor.model;

public class slkstateWithBLOBs extends slkstate {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column slkstate.exitinfo
     *
     * @mbg.generated Fri Jul 26 16:10:58 CST 2019
     */
    private String exitinfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column slkstate.doinfo
     *
     * @mbg.generated Fri Jul 26 16:10:58 CST 2019
     */
    private String doinfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column slkstate.entry
     *
     * @mbg.generated Fri Jul 26 16:10:58 CST 2019
     */
    private String entry;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column slkstate.exitinfo
     *
     * @return the value of slkstate.exitinfo
     *
     * @mbg.generated Fri Jul 26 16:10:58 CST 2019
     */
    public String getExitinfo() {
        return exitinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column slkstate.exitinfo
     *
     * @param exitinfo the value for slkstate.exitinfo
     *
     * @mbg.generated Fri Jul 26 16:10:58 CST 2019
     */
    public void setExitinfo(String exitinfo) {
        this.exitinfo = exitinfo == null ? null : exitinfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column slkstate.doinfo
     *
     * @return the value of slkstate.doinfo
     *
     * @mbg.generated Fri Jul 26 16:10:58 CST 2019
     */
    public String getDoinfo() {
        return doinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column slkstate.doinfo
     *
     * @param doinfo the value for slkstate.doinfo
     *
     * @mbg.generated Fri Jul 26 16:10:58 CST 2019
     */
    public void setDoinfo(String doinfo) {
        this.doinfo = doinfo == null ? null : doinfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column slkstate.entry
     *
     * @return the value of slkstate.entry
     *
     * @mbg.generated Fri Jul 26 16:10:58 CST 2019
     */
    public String getEntry() {
        return entry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column slkstate.entry
     *
     * @param entry the value for slkstate.entry
     *
     * @mbg.generated Fri Jul 26 16:10:58 CST 2019
     */
    public void setEntry(String entry) {
        this.entry = entry == null ? null : entry.trim();
    }
}