package extractor.model;

public class slkstate {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column slkstate.ID
     *
     * @mbg.generated Wed Jul 24 16:08:34 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column slkstate.taskid
     *
     * @mbg.generated Wed Jul 24 16:08:34 CST 2019
     */
    private String taskid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column slkstate.faultstate
     *
     * @mbg.generated Wed Jul 24 16:08:34 CST 2019
     */
    private String faultstate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column slkstate.ID
     *
     * @return the value of slkstate.ID
     *
     * @mbg.generated Wed Jul 24 16:08:34 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column slkstate.ID
     *
     * @param id the value for slkstate.ID
     *
     * @mbg.generated Wed Jul 24 16:08:34 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column slkstate.taskid
     *
     * @return the value of slkstate.taskid
     *
     * @mbg.generated Wed Jul 24 16:08:34 CST 2019
     */
    public String getTaskid() {
        return taskid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column slkstate.taskid
     *
     * @param taskid the value for slkstate.taskid
     *
     * @mbg.generated Wed Jul 24 16:08:34 CST 2019
     */
    public void setTaskid(String taskid) {
        this.taskid = taskid == null ? null : taskid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column slkstate.faultstate
     *
     * @return the value of slkstate.faultstate
     *
     * @mbg.generated Wed Jul 24 16:08:34 CST 2019
     */
    public String getFaultstate() {
        return faultstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column slkstate.faultstate
     *
     * @param faultstate the value for slkstate.faultstate
     *
     * @mbg.generated Wed Jul 24 16:08:34 CST 2019
     */
    public void setFaultstate(String faultstate) {
        this.faultstate = faultstate == null ? null : faultstate.trim();
    }
}