package extractor.model;

public class transition {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transition.TransitionID
     *
     * @mbg.generated Sat Apr 27 21:00:48 CST 2019
     */
    private Integer transitionid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transition.Guide
     *
     * @mbg.generated Sat Apr 27 21:00:48 CST 2019
     */
    private String guide;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transition.Name
     *
     * @mbg.generated Sat Apr 27 21:00:48 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transition.trigger
     *
     * @mbg.generated Sat Apr 27 21:00:48 CST 2019
     */
    private Integer trigger;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transition.TransitionID
     *
     * @return the value of transition.TransitionID
     *
     * @mbg.generated Sat Apr 27 21:00:48 CST 2019
     */
    public Integer getTransitionid() {
        return transitionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transition.TransitionID
     *
     * @param transitionid the value for transition.TransitionID
     *
     * @mbg.generated Sat Apr 27 21:00:48 CST 2019
     */
    public void setTransitionid(Integer transitionid) {
        this.transitionid = transitionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transition.Guide
     *
     * @return the value of transition.Guide
     *
     * @mbg.generated Sat Apr 27 21:00:48 CST 2019
     */
    public String getGuide() {
        return guide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transition.Guide
     *
     * @param guide the value for transition.Guide
     *
     * @mbg.generated Sat Apr 27 21:00:48 CST 2019
     */
    public void setGuide(String guide) {
        this.guide = guide == null ? null : guide.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transition.Name
     *
     * @return the value of transition.Name
     *
     * @mbg.generated Sat Apr 27 21:00:48 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transition.Name
     *
     * @param name the value for transition.Name
     *
     * @mbg.generated Sat Apr 27 21:00:48 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transition.trigger
     *
     * @return the value of transition.trigger
     *
     * @mbg.generated Sat Apr 27 21:00:48 CST 2019
     */
    public Integer getTrigger() {
        return trigger;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transition.trigger
     *
     * @param trigger the value for transition.trigger
     *
     * @mbg.generated Sat Apr 27 21:00:48 CST 2019
     */
    public void setTrigger(Integer trigger) {
        this.trigger = trigger;
    }
}