package extractor.model;

public class transitionstate {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transitionstate.id
     *
     * @mbg.generated Tue Apr 30 11:57:57 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transitionstate.source
     *
     * @mbg.generated Tue Apr 30 11:57:57 CST 2019
     */
    private Integer source;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transitionstate.out
     *
     * @mbg.generated Tue Apr 30 11:57:57 CST 2019
     */
    private Integer out;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transitionstate.transitionid
     *
     * @mbg.generated Tue Apr 30 11:57:57 CST 2019
     */
    private Integer transitionid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transitionstate.id
     *
     * @return the value of transitionstate.id
     *
     * @mbg.generated Tue Apr 30 11:57:57 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transitionstate.id
     *
     * @param id the value for transitionstate.id
     *
     * @mbg.generated Tue Apr 30 11:57:57 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transitionstate.source
     *
     * @return the value of transitionstate.source
     *
     * @mbg.generated Tue Apr 30 11:57:57 CST 2019
     */
    public Integer getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transitionstate.source
     *
     * @param source the value for transitionstate.source
     *
     * @mbg.generated Tue Apr 30 11:57:57 CST 2019
     */
    public void setSource(Integer source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transitionstate.out
     *
     * @return the value of transitionstate.out
     *
     * @mbg.generated Tue Apr 30 11:57:57 CST 2019
     */
    public Integer getOut() {
        return out;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transitionstate.out
     *
     * @param out the value for transitionstate.out
     *
     * @mbg.generated Tue Apr 30 11:57:57 CST 2019
     */
    public void setOut(Integer out) {
        this.out = out;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transitionstate.transitionid
     *
     * @return the value of transitionstate.transitionid
     *
     * @mbg.generated Tue Apr 30 11:57:57 CST 2019
     */
    public Integer getTransitionid() {
        return transitionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transitionstate.transitionid
     *
     * @param transitionid the value for transitionstate.transitionid
     *
     * @mbg.generated Tue Apr 30 11:57:57 CST 2019
     */
    public void setTransitionid(Integer transitionid) {
        this.transitionid = transitionid;
    }
}